In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
data=np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
data=data.sample(5)
data

    R&D Spend  Administration  Marketing Spend  Profit
17        9.0            15.0             28.0    13.0
29        7.0            15.0             11.0    10.0
30        6.0            12.0              9.0    10.0
31        6.0            15.0              9.0    10.0
25        6.0            14.0             14.0    11.0

In [15]:
data=data.iloc[:,0:3]
data

    R&D Spend  Administration  Marketing Spend
17        9.0            15.0             28.0
29        7.0            15.0             11.0
30        6.0            12.0              9.0
31        6.0            15.0              9.0
25        6.0            14.0             14.0

In [20]:
data.iloc[1,0]=np.NaN
data.iloc[3,1]=np.NaN
data.iloc[4,2]=np.NaN
data

    R&D Spend  Administration  Marketing Spend
17        9.0            15.0             28.0
29        NaN            15.0             11.0
30        6.0            12.0              9.0
31        6.0             NaN              9.0
25        6.0            14.0              NaN

# Iteration 0

In [31]:
df0=pd.DataFrame()
df0['R&D Spend']=data['R&D Spend'].fillna(data['R&D Spend'].mean())
df0['Administration']=data['Administration'].fillna(data['Administration'].mean())
df0['Marketing Spend']=data['Marketing Spend'].fillna(data['Marketing Spend'].mean())

In [32]:
df0

    R&D Spend  Administration  Marketing Spend
17       9.00            15.0            28.00
29       6.75            15.0            11.00
30       6.00            12.0             9.00
31       6.00            14.0             9.00
25       6.00            14.0            14.25

In [34]:
df1=df0.copy()
df1.iloc[1,0]=np.NaN
df1

    R&D Spend  Administration  Marketing Spend
17        9.0            15.0            28.00
29        NaN            15.0            11.00
30        6.0            12.0             9.00
31        6.0            14.0             9.00
25        6.0            14.0            14.25

In [35]:
from sklearn.linear_model import LinearRegression

In [49]:
x=df1.iloc[[0,2,3,4],1:3]
x

    Administration  Marketing Spend
17            15.0            28.00
30            12.0             9.00
31            14.0             9.00
25            14.0            14.25

In [50]:
y=df1.iloc[[0,2,3,4],0]
y

17    9.0
30    6.0
31    6.0
25    6.0
Name: R&D Spend, dtype: float64

In [51]:
clf=LinearRegression()
clf.fit(x,y)
clf.predict(df1.iloc[1,1:3].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([5.88173337])

In [52]:
df1.iloc[1,0]=5.88

In [53]:
df1

    R&D Spend  Administration  Marketing Spend
17       9.00            15.0            28.00
29       5.88            15.0            11.00
30       6.00            12.0             9.00
31       6.00            14.0             9.00
25       6.00            14.0            14.25

In [57]:
df1.iloc[3,1]=np.NaN
df1

    R&D Spend  Administration  Marketing Spend
17       9.00            15.0            28.00
29       5.88            15.0            11.00
30       6.00            12.0             9.00
31       6.00             NaN             9.00
25       6.00            14.0            14.25

In [56]:
x=df1.iloc[[0,1,2,4],[0,2]]
x

    R&D Spend  Marketing Spend
17       9.00            28.00
29       5.88            11.00
30       6.00             9.00
25       6.00            14.25

In [58]:
y=df1.iloc[[0,1,2,4],1]
y

17    15.0
29    15.0
30    12.0
25    14.0
Name: Administration, dtype: float64

In [59]:
clf.fit(x,y)

LinearRegression()

In [63]:
clf.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12.68969897])

In [64]:
df1.iloc[3,1]=12.68

In [71]:
df1.iloc[4,2]=np.NaN
df1

    R&D Spend  Administration  Marketing Spend
17       9.00           15.00             28.0
29       5.88           15.00             11.0
30       6.00           12.00              9.0
31       6.00           12.68              9.0
25       6.00           14.00              NaN

In [70]:
x=df1.iloc[[0,1,2,3],[0,1]]
x

    R&D Spend  Administration
17       9.00           15.00
29       5.88           15.00
30       6.00           12.00
31       6.00           12.68

In [72]:
y=df1.iloc[[0,1,2,3],2]
y

17    28.0
29    11.0
30     9.0
31     9.0
Name: Marketing Spend, dtype: float64

In [74]:
clf.fit(x,y)

LinearRegression()

In [75]:
clf.predict(df1.iloc[4,[0,1]].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([10.62385165])

In [76]:
df1.iloc[4,-1]=10.62

In [77]:
df1

    R&D Spend  Administration  Marketing Spend
17       9.00           15.00            28.00
29       5.88           15.00            11.00
30       6.00           12.00             9.00
31       6.00           12.68             9.00
25       6.00           14.00            10.62

In [95]:
df0-df1

    R&D Spend  Administration  Marketing Spend
17       0.00            0.00             0.00
29       0.87            0.00             0.00
30       0.00            0.00             0.00
31       0.00            1.32             0.00
25       0.00            0.00             3.63

In [96]:
df2=df1.copy()
df2.iloc[1,0]=np.NaN
df2

    R&D Spend  Administration  Marketing Spend
17        9.0           15.00            28.00
29        NaN           15.00            11.00
30        6.0           12.00             9.00
31        6.0           12.68             9.00
25        6.0           14.00            10.62

In [97]:
x=df2.iloc[[0,2,3,4],1:3]
y=df2.iloc[[0,2,3,4],0]
clf.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([57.02313184])

In [98]:
df2.iloc[1,0]=57.02
df2

    R&D Spend  Administration  Marketing Spend
17       9.00           15.00            28.00
29      57.02           15.00            11.00
30       6.00           12.00             9.00
31       6.00           12.68             9.00
25       6.00           14.00            10.62

In [100]:
df2.iloc[3,1] = np.NaN
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12.87227786])

In [103]:
df2.iloc[3,1]=12.87
df2

    R&D Spend  Administration  Marketing Spend
17       9.00           15.00            28.00
29      57.02           15.00            11.00
30       6.00           12.00             9.00
31       6.00           12.87             9.00
25       6.00           14.00            10.62

In [104]:
df2.iloc[4,-1] = np.NaN

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([20.71713306])

In [105]:
df2.iloc[4,-1] = 20.71

In [106]:
df2

    R&D Spend  Administration  Marketing Spend
17       9.00           15.00            28.00
29      57.02           15.00            11.00
30       6.00           12.00             9.00
31       6.00           12.87             9.00
25       6.00           14.00            20.71

In [107]:
df2-df1

    R&D Spend  Administration  Marketing Spend
17       0.00            0.00             0.00
29      51.14            0.00             0.00
30       0.00            0.00             0.00
31       0.00            0.19             0.00
25       0.00            0.00            10.09

In [109]:
df3=df2.copy()
df3.iloc[1,0] = np.NaN

df3

    R&D Spend  Administration  Marketing Spend
17        9.0           15.00            28.00
29        NaN           15.00            11.00
30        6.0           12.00             9.00
31        6.0           12.87             9.00
25        6.0           14.00            20.71

In [110]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([6.13725968])

In [111]:
df3.iloc[1,0] = 6.13

In [113]:
df3.iloc[3,1] = np.NaN
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([13.30954055])

In [114]:
df3.iloc[3,1] = 13.30

In [115]:
df3-df2

    R&D Spend  Administration  Marketing Spend
17       0.00            0.00              0.0
29     -50.89            0.00              0.0
30       0.00            0.00              0.0
31       0.00            0.43              0.0
25       0.00            0.00              0.0